server:
  port: ${PORT:8080}

dotenv:
  enabled: true

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    co.com: DEBUG

service:
  auth:
    token: ${SERVICE_AUTH_TOKEN}
admin:
  secret:
    token: ${ADMIN_SECRET_TOKEN}
  security:
    jwt-secret: ${ADMIN_SECURITY_JWT_SECRET}
  credentials:
    user: ${ADMIN_CREDENTIALS_USER}
    password: ${ADMIN_CREDENTIALS_PASSWORD}
users:
  backend:
    url: ${USERS_BACKEND_URL:http://localhost:8080}
    token: ${USERS_BACKEND_TOKEN}
firebase:
  enabled: true
