spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crduels?connectTimeout=10&sslmode=prefer

service:
  auth:
    token: ${SERVICE_AUTH_TOKEN:changeme}
  admin:
    secret:
      token: ${ADMIN_SECRET_TOKEN:changeme}
