spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?connectTimeout=10&sslmode=prefer
    username: ${PGUSER}
    password: ${PGPASSWORD}

service:
  auth:
    token: ${SERVICE_AUTH_TOKEN:changeme}
  admin:
    secret:
      token: ${ADMIN_SECRET_TOKEN:changeme}
    credentials:
      user: ${ADMIN_CREDENTIALS_USER:admin}
      password: ${ADMIN_CREDENTIALS_PASSWORD:admin}
jwt:
  secret: ${JWT_SECRET:changeme}
