spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crduels?connectTimeout=10&sslmode=prefer

service:
  auth:
    token: ${SERVICE_AUTH_TOKEN:changeme}
  admin:
    secret:
      token: ${ADMIN_SECRET_TOKEN:changeme}
    credentials:
      user: ${ADMIN_CREDENTIALS_USER:admin}
      password: ${ADMIN_CREDENTIALS_PASSWORD:admin}

security:
  jwt-secret: ${SECURITY_JWT_SECRET:${ADMIN_SECURITY_JWT_SECRET:5e8f0bc1f6c34fdfadcb5c1249eb4d77b91c8f2d0316fabbf90c1aaaf7b39cdd}}
