spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?connectTimeout=10&sslmode=prefer
    username: ${PGUSER}
    password: ${PGPASSWORD}

service:
  auth:
    token: ${SERVICE_AUTH_TOKEN:changeme}
